### ISSUE TITLE
Curve2 theme issues

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#7259]
There are a number of issues with Curve2 that should be addressed. Some only require changes to CSS and could therefore theoretically be put off until 2.1.1. However, many others require HTML or JavaScript changes and therefore need to be addressed before 2.1.0. This is because we don't want theme authors using Curve2 as a base to be thrown for a loop by major changes to the default templates in 2.1.1 or beyond.

The following is not an exhaustive list, and it will probably be updated as more issues are identified.

- [x] Cramped layout around topic info on message index on small screens. (Fixed in #7260)
- [x] Cramped layout around post body on message index on small screens. (Fixed in #7260)
- [x] Post header shows too much data on small screens. (Fixed in #7260)
- [x] Feedback to date suggests people prefer the member’s title and group above the avatar rather than below. (Fixed in #7260)
- [x] Layout around the Like button is too cramped, especially on small screens but even on larger ones sometimes. (Fixed in #7260)
- [x] Posting buttons don’t float to the right on small screens. (Fixed in #7260)
- [x] Quick buttons still appear in the post header area (like in 2.0.x) in the topic summary, search results, the moderation centre, etc. These should be moved to be consistent with the layout used in the topic display.
- [x] The "Unread Posts" and "Updated Topics" links clutter up the linktree on small screens, and even on larger screens when the linktree is long. (Fixed in #7260)
- [x] Empty `lastpost` divs on the message index should be collapsed on small screens. (Fixed in #7260)
- [x] The width of "jump to" select menus changes unpredictably during user interaction. (Fixed in #7260)

- [x] Although the innermost part of the page index template is consistent, the wrapper divs placed around it are quite inconsistent across different templates, potentially causing theme authors all sorts of headaches. (Fixed in #7261)
- [x] The CSS used for the member’s name and position in the profile summary is unlike anything else in the theme. It looks nice in and of itself, sure, but it is inconsistent. (Fixed in #7261)
- [x] The `cat_bar` style for headings is designed to appear immediately above a table or visually similar structure, but in fact it is often appears on its own, which looks weird. (Fixed in #7261)
    - In some cases, rounded bottom corners should be applied to the `cat_bar` div.
    - In other cases, the following div should have the `noup` class applied to it in order to visually connect it with the preceding cat_bar
    - In yet other cases, the `cat_bar` class should be changed to some other class.
    - In a few cases, the entire `cat_bar` div is useless or redundant and can probably be removed.
- [x] When a category is collapsed on the board index and the user clicks on a category link in the linktree, the browser window may end up autoscrolling to the wrong position on the board index. This happens because the board table below a collapsed `cat_bar` is initially visible when the page loads before being immediately hidden by JavaScript, with the result that the browser initially autoscrolls the window to the original position of the target category. An easy fix is to make the collapsed content already hidden when the page first loads. (Fixed in #7261)
- [x] When showing a board, a topic, or even search results or recent posts, very similar information is presented to the user about what is being shown (e.g. board name and description, topic subject and author info, search query string, etc.), but we use at least three entirely different UI conventions to present this info. These should be made consistent. Since the UI used for topic display is the best of the options, the others should probably be changed to resemble that. (Fixed in #7261)
- [x] For no apparent reason, topic moderation UI is provided on search results when the “Show results as messages” option is not selected. This makes no sense and should be removed. (Fixed in #7261)
- [x] There is significant inconsistency between the presentation of posts in the topic display from the presentation of posts in search results, member profiles, the moderation centre, etc. The presentation should be made as consistent as possible. (Fixed in #7261)
- [x] The error log templates are (and need to be) more like post display templates that like the other log templates, but the overall UI for the error log can still be made more consistent with our UI conventions elsewhere than it is now. (Fixed in #7261)
- ~There is no “Select all” checkbox provided in the topic display when the moderator has chosen to use checkboxes for quick moderation.~
- [x] The login link that appears in the `top_section` bar for guests is easy to overlook. (Fixed in #7267)
- [x] The "Sign Up" button appears in the main menu bar, whereas all other pieces of profile related UI (profile menu, PMs, alerts, login link) appear in the `top_section` bar. (Fixed in #7267)

**Comment by sbulen** [comment]
I really think you should reconsider this milestone.  No discussion internally or otherwise.  Not good planning, coordination, or discussion.

**Comment by Sesquipedalian** [comment]
Er, is this not the place to discuss such things, @sbulen?

At any rate, as you can see I have just submitted PRs to address these all but two of these issues, so perhaps it won't be such a delay as you are worried about. 😉

**Comment by sbulen** [comment]
You are welcome to join the internal team discussions that have been taking place!

**Comment by Arantor** [comment]
> There is no “Select all” checkbox provided in the topic display when the moderator has chosen to use checkboxes for quick moderation

How often would it actually make sense to do just that? If you’re looking to delete all the posts, delete the topic (because selecting all the posts and deleting isn’t going to work as expected), or if splitting odds are the correct operation is to split the entire topic at that point.

> The "Sign Up" button appears in the main menu bar, whereas all other pieces of profile related UI (profile menu, PMs, alerts, login link) appear in the top_section bar.

I couldn’t convince people to drop it from the main menu…

**Comment by LexArma** [comment]
I could actually see use for a select all option, sometimes it's easier and faster to select a whole page worth when cleaning spam - and it can work as expected if you are not on the first page, but you can also deselect individual messages you don't want to delete after all.

**Comment by Arantor** [comment]
Is that really a common operation, though? Deleting page n of a topic? Wouldn’t it be quicker to split and delete whole topic at that point?

I’m mostly just trying to (gently) suggest this is scope creep for a relative edge case, rather than suggesting it would be a major QoL improvement. I want to see 2.1 released!

**Comment by LexArma** [comment]
It's not really a huge loss if the option isn't there I guess, just saying I can see a use case that's all. :)

**Comment by DiegoAndresCortes** [comment]
I agree with that, is not a common usage other than splitting 2-3 posts. We usually just immediately delete what needs to be deleted.

**Comment by Sesquipedalian** [comment]
> Is that really a common operation, though?

I find your argument convincing.
